[build]
  command = "cd root && npm install && npm run build && cd ../admin && npm install && npm run build && cd ../premium-adjustment && npm install && npm run build && cd .. && rm -rf deploy && mkdir deploy && cp -r root/dist deploy/root && cp -r admin/dist deploy/admin && cp -r premium-adjustment/dist deploy/premium-adjustment"
  publish = "deploy"

[[redirects]]
  from = "/admin/*"
  to = "/admin/index.html"
  status = 200

[[redirects]]
  from = "/premium-adjustment/*"
  to = "/premium-adjustment/index.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/root/index.html"
  status = 200
